version: 1.2.{build}
image: Visual Studio 2017
init:
- ps: |
    Install-Package Configuration -Provider PowerShellGet -Minimum 1.0 -Force -ForceBootstrap
    Install-Package Pester -Provider PowerShellGet -Minimum 4.0 -Force -SkipPublisherCheck
install:
- ps: |
    .\Build.ps1 -Step Clean, Update -Verbose
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1 -Step Build -Verbose
test_script:
- ps: .\Build.ps1 -Step Test -Verbose
deploy_script:
- ps: .\Build.ps1 -Step Package -Verbose | % { Push-AppveyorArtifact $_.FullName }
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: poshcode
  template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}>\nCommit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:\n_{{commitMessage}}_{{#messages}}\n{{.}}{{/messages}}"
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
